/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myapp;

import myapp.foo.Bar;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    private static final Logger logger;
    static {
        // ConfigureLogger.configure();
        logger = LogManager.getLogger();
    }

    public String getGreeting() {
        return "Hello!";
    }

    public static void main(String[] args) {
        logger.debug("Entering application.");
        Bar bar = new Bar();
        if (!bar.doIt()) {
            logger.error("Some error");
        }
        logger.trace("Exiting application.");
    }

}
